---
extends:
  - stylelint-config-standard
rules:
  indentation: 2
  string-quotes: single
  no-duplicate-selectors: true
  color-hex-case: lower
  color-hex-length: short
  selector-no-qualifying-type: null
  selector-combinator-space-after: always
  selector-attribute-quotes: always
  declaration-block-trailing-semicolon: always
  declaration-colon-space-before: never
  declaration-colon-space-after: always
  function-url-quotes: always
  comment-whitespace-inside: always
  media-feature-colon-space-after: always
  media-feature-colon-space-before: never