name: Scripts CI

on:
  pull_request:
  push:
    branches: [develop, main, master]

jobs:
  script-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run repository checks
        run: ./scripts/run-ci-checks.sh
